const CARS = [
  // ---------- OWNED ----------
  {
    brand: "Toyota",
    model: "Starlet",
    engine: "1.3",
    power: "75 HP",
    year: 1989,
    owned: "2002 – 2010",
    category: "Owned",
    photo: "photos/starlet.png",
  },
  {
    brand: "Skoda",
    model: "Fabia",
    engine: "1.2",
    power: "105 HP",
    year: 2010,
    owned: "2010 – 2019",
    category: "Owned",
    photo: "photos/fabia.png",
  },
  {
    brand: "Suzuki",
    model: "Vitara",
    engine: "1.4",
    power: "140 HP",
    year: 2019,
    owned: "2019 – 2022",
    category: "Owned",
    photo: "photos/vitara.png",
  },
  {
    brand: "Toyota",
    model: "Aygo",
    engine: "1.0",
    power: "60 HP",
    year: 2021,
    owned: "2021 - σήμερα",
    category: "Owned",
    photo: "photos/aygo.png",
  },
  {
    brand: "Hyundai",
    model: "Getz",
    engine: "1.4",
    power: "75 HP",
    year: 2006,
    owned: "2019 - 2021",
    category: "Owned",
    photo: "photos/getz.png",
  },

  // ---------- SISSY ----------
  {
    brand: "Suzuki",
    model: "Ignis",
    engine: "1.4",
    power: "85 HP",
    year: 2024,
    owned: "2005 – 2010",
    category: "Sissy",
    photo: "photos/ignis.png",
  },

  // ---------- Company Cars ----------
  {
    brand: "DS",
    model: "7 Crossback",
    engine: "PHEV 1.6",
    power: "225 HP",
    year: 2018,
    owned: "2022 – 2026",
    category: "Company Car",
    photo: "photos/ds.png",
  },
  {
    brand: "Smart",
    model: "#5",
    engine: "Ηλεκτρικό",
    power: "600 HP",
    year: 2026,
    owned: "2026 – σήμερα",
    category: "Company Car",
    photo: "photos/smart.png",
  },

  // ---------- FATHER ----------
  {
    brand: "Skoda",
    model: "Target 120",
    engine: "1.2",
    power: "52 HP",
    year: 1986,
    owned: "2000",
    category: "Father",
    photo: "photos/target.png",
  },
  {
    brand: "Nissan",
    model: "Almera GX",
    engine: "1.6",
    power: "100 HP",
    year: 1998,
    owned: "2001",
    category: "Father",
    photo: "photos/almera.png",
  },

  // ---------- 3RD PARTY ----------
  {
    brand: "Mercedes",
    model: "GD290 Military",
    engine: "2.9",
    power: "",
    year: "",
    owned: "2006",
    category: "3rd Party",
    photo: "photos/gd290.png",
  },
  {
    brand: "Mitsubishi",
    model: "Pajero",
    engine: "",
    power: "",
    year: 1982,
    owned: "",
    category: "3rd Party",
    photo: "photos/pajero.png",
  },
  {
    brand: "Citroen",
    model: "C3",
    engine: "",
    power: "",
    year: 2023,
    owned: "",
    category: "Rental",
    photo: "photos/c3.png",
  },
  {
    brand: "Toyota",
    model: "Yaris",
    engine: "",
    power: "",
    year: 2022,
    owned: "",
    category: "Rental",
    photo: "photos/yaris.png",
  },
  {
    brand: "Honda",
    model: "Civic",
    engine: "",
    power: "",
    year: 2000,
    owned: "",
    category: "3rd Party",
    photo: "photos/civic.png",
  },
  {
    brand: "Toyota",
    model: "Rav4 XA30",
    engine: "2.2",
    power: "150 HP",
    year: 2010,
    owned: "",
    category: "3rd Party",
    photo: "photos/rav4.png",
  },
  {
    brand: "Suzuki",
    model: "Jimny",
    engine: "1.3",
    power: "",
    year: 2003,
    owned: "",
    category: "3rd Party",
    photo: "photos/jimny.png",
  },
  {
    brand: "Peugeot",
    model: "3008",
    engine: "1.5",
    power: "",
    year: "2019",
    owned: "",
    category: "Replacement",
    photo: "photos/3008.png",
  },
  {
    brand: "Ford",
    model: "Puma ST-Line",
    engine: "1.5",
    power: "150 HP",
    year: "2020",
    owned: "",
    category: "Replacement",
    photo: "photos/puma.png",
  },
  {
    brand: "Audi",
    model: "Q3 Sportsback",
    engine: "1.5",
    power: "120 HP",
    year: "2022",
    owned: "",
    category: "Replacement",
    photo: "photos/q3.png",
  },
  {
    brand: "Volkswagen",
    model: "Tiguan life",
    engine: "1.5",
    power: "",
    year: "2024",
    owned: "",
    category: "Replacement",
    photo: "photos/tiguan.png",
  },
  {
    brand: "BMW",
    model: "X1 sDrive20i",
    engine: "1.5",
    power: "170 HP",
    year: "2025",
    owned: "",
    category: "Replacement",
    photo: "photos/x1.png",
  },
];
